const PageWithNavActions = {
  SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
  SET_ACTIONS_LEFT: "SET_ACTIONS_LEFT",
  SET_ACTIONS_RIGHT: "SET_ACTIONS_RIGHT",
  SET_VISIBLE: "SET_VISIBLE",
};
export default PageWithNavActions;
