const TotalBillActions = {
  SET_HOME_DATA: "SET_HOME_DATA",
  SET_DISCOUNT_TABLE_DATA: "SET_DISCOUNT_TABLE_DATA",
  SET_FREE_TABLE_DATA: "SET_FREE_TABLE_DATA",
  SET_CURRENT_SEARCH_PARAMS: "CURRENT_SEARCH_PARAMS",
};
export default TotalBillActions;
